### PR TITLE
Reflect latest changes from single file ontology to the split ontology and shapes files

### PR DESCRIPTION
**Pull request by rivettp**

### CODE REVIEW

**Comment by FroehlichMarcel** [comment]
Okay, thanks Pete.

**Review by jgeluk — APPROVED** [review]

**Review by FroehlichMarcel — APPROVED** [review]
ok

**Comment by nvar** [comment]
@rivettp There are some things missing like class Domain and the property dprod:offersDistribution has been replaced by isAccessServiceOf
Maybe you just copy the existing artifacts as is from dprod.tll to the corresponding files?

**Comment by nvar** [comment]
@rivettp Can you add the classes Protocol and Domain in the ontology file and the corresponding Shapes ? 
Also can you remove the belongsToDataset property? It is superseded with the isDistributionOf

**Review by nvar — APPROVED** [review]

**Pull request merged**
